name: Construir e implantar aplicação .NET para aplicação em contêineres bankchallengeapi-app-20231215023
on:
  push:
    branches:
    - master
env:
  CONTAINER_APP_CONTAINER_NAME: bankchallengeapi
  CONTAINER_APP_NAME: bankchallengeapi-app-20231215023
  CONTAINER_APP_RESOURCE_GROUP_NAME: bankchallenge
  CONTAINER_REGISTRY_LOGIN_SERVER: bankchallengeapi20231215023943.azurecr.io
  DOCKER_FILE_PATH: BankChallenge.API/Dockerfile
  PROJECT_NAME_FOR_DOCKER: bankchallengeapi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.BankChallengeAPI20231215023943_USERNAME_D8F2 }}
        password: ${{ secrets.BankChallengeAPI20231215023943_PASSWORD_D8F2 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.bankchallengeapi_app_20231215023_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.BankChallengeAPI20231215023943_USERNAME_D8F2 }} --password ${{ secrets.BankChallengeAPI20231215023943_PASSWORD_D8F2 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
